name: Build

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]        
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-package: 'jdk'
          java-version: '17'
          distribution: 'zulu'
      - uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.11.1.1200
      - run: clojure -Xtest
      - run: clojure -Mdoc
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          author_name: Thom Lawrence
          author_email: thom@lemonwatcher.com
          message: 'Updating Marginalia docs.'
